name: r-env
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - bleach=3.1.5=py_0
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.6.20=py38h32f6830_0
  - cftime=1.1.3=py38h8790de6_0
  - curl=7.69.1=hbc83047_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - fribidi=1.0.5=h7b6447c_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_9
  - glib=2.63.1=h3eb4bd4_1
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - gsl=2.4=h14c3975_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf4=4.2.13=0
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=he6710b0_3
  - importlib-metadata=1.6.1=py38_0
  - importlib_metadata=1.6.1=0
  - ipykernel=5.3.0=py38h5ca1d4c_0
  - ipython=7.15.0=py38_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.0=py38_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py38_0
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py38_0
  - krb5=1.17.1=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=14_openblas
  - libnetcdf=4.7.3=hb80b6cc_0
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_0
  - make=4.2.1=h1bed415_1
  - markupsafe=1.1.1=py38h7b6447c_0
  - mistune=0.8.4=py38h7b6447c_1000
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - netcdf4=1.5.3=py38hbf33ddf_0
  - notebook=6.0.3=py38_0
  - numpy=1.18.5=py38h8854b6b_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=py_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - pango=1.42.4=h5aa6e80_1
  - parso=0.7.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.1.1=py38_1
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py38_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyrsistent=0.16.0=py38h7b6447c_0
  - python=3.8.3=hcff3b4d_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pyzmq=18.1.1=py38he6710b0_0
  - qt=5.6.3=h8bf5577_3
  - r-askpass=1.0=r36h14c3975_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-backports=1.1.4=r36h96ca727_0
  - r-base=3.6.1=haffb61f_2
  - r-base64enc=0.1_3=r36h96ca727_4
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-boot=1.3_20=r36h6115d3f_0
  - r-broom=0.5.2=r36h6115d3f_0
  - r-callr=3.2.0=r36h6115d3f_0
  - r-caret=6.0_83=r36h96ca727_0
  - r-cellranger=1.1.0=r36h6115d3f_0
  - r-class=7.3_15=r36h96ca727_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-clipr=0.6.0=r36h6115d3f_0
  - r-cluster=2.0.8=r36ha65eedd_0
  - r-codetools=0.2_16=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h96ca727_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-curl=3.3=r36h96ca727_0
  - r-data.table=1.12.2=r36h96ca727_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h96ca727_0
  - r-dplyr=0.8.0.1=r36h29659fb_0
  - r-ellipsis=0.1.0=r36h96ca727_0
  - r-essentials=3.6.0=r36_0
  - r-evaluate=0.13=r36h6115d3f_0
  - r-fansi=0.4.0=r36h96ca727_0
  - r-forcats=0.4.0=r36h6115d3f_0
  - r-foreach=1.4.4=r36h6115d3f_0
  - r-foreign=0.8_71=r36h96ca727_0
  - r-formatr=1.6=r36h6115d3f_0
  - r-fs=1.2.7=r36h29659fb_0
  - r-generics=0.0.2=r36h6115d3f_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-glmnet=2.0_16=r36ha65eedd_0
  - r-glue=1.3.1=r36h96ca727_0
  - r-gower=0.2.0=r36h96ca727_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-haven=2.1.0=r36h29659fb_0
  - r-hexbin=1.27.2=r36ha65eedd_0
  - r-highr=0.8=r36h6115d3f_0
  - r-hms=0.4.2=r36h6115d3f_0
  - r-htmltools=0.3.6=r36h29659fb_0
  - r-htmlwidgets=1.3=r36h6115d3f_0
  - r-httpuv=1.5.1=r36h29659fb_0
  - r-httr=1.4.0=r36h6115d3f_0
  - r-ipred=0.9_8=r36h96ca727_0
  - r-irdisplay=0.7.0=r36h6115d3f_0
  - r-irkernel=0.8.15=r36_0
  - r-iterators=1.0.10=r36h6115d3f_0
  - r-jsonlite=1.6=r36h96ca727_0
  - r-kernsmooth=2.23_15=r36ha65eedd_4
  - r-knitr=1.22=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_4
  - r-later=0.8.0=r36h29659fb_0
  - r-lattice=0.20_38=r36h96ca727_0
  - r-lava=1.6.5=r36h6115d3f_0
  - r-lazyeval=0.2.2=r36h96ca727_0
  - r-lubridate=1.7.4=r36h29659fb_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-maps=3.3.0=r36h96ca727_0
  - r-markdown=0.9=r36h96ca727_0
  - r-mass=7.3_51.3=r36h96ca727_0
  - r-matrix=1.2_17=r36h96ca727_0
  - r-mgcv=1.8_28=r36h96ca727_0
  - r-mime=0.6=r36h96ca727_0
  - r-modelmetrics=1.2.2=r36h29659fb_0
  - r-modelr=0.1.4=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-ncdf4=1.16.1=r36h96ca727_0
  - r-nlme=3.1_139=r36ha65eedd_0
  - r-nnet=7.3_12=r36h96ca727_0
  - r-numderiv=2016.8_1=r36h6115d3f_0
  - r-openssl=1.3=r36h96ca727_0
  - r-pbdzmq=0.3_3=r36h5455479_1
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.4=r36h29659fb_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-processx=3.3.0=r36h96ca727_0
  - r-prodlim=2018.04.18=r36h29659fb_0
  - r-progress=1.2.0=r36h6115d3f_0
  - r-promises=1.0.1=r36h29659fb_0
  - r-ps=1.3.0=r36h96ca727_0
  - r-purrr=0.3.2=r36h96ca727_0
  - r-quantmod=0.4_14=r36h6115d3f_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-randomforest=4.6_14=r36ha65eedd_0
  - r-rbokeh=0.6.3=r36_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h29659fb_0
  - r-rcpproll=0.3.0=r36h29659fb_0
  - r-readr=1.3.1=r36h29659fb_0
  - r-readxl=1.3.1=r36h29659fb_0
  - r-recipes=0.1.5=r36h6115d3f_0
  - r-recommended=3.6.0=r36_0
  - r-rematch=1.0.1=r36h6115d3f_0
  - r-repr=0.19.2=r36h6115d3f_0
  - r-reprex=0.2.1=r36h6115d3f_0
  - r-reshape2=1.4.3=r36h29659fb_0
  - r-rlang=0.3.4=r36h96ca727_0
  - r-rmarkdown=1.12=r36h6115d3f_0
  - r-rpart=4.1_15=r36h96ca727_0
  - r-rstudioapi=0.10=r36h6115d3f_0
  - r-rvest=0.3.3=r36h6115d3f_0
  - r-scales=1.0.0=r36h29659fb_0
  - r-selectr=0.4_1=r36h6115d3f_0
  - r-shiny=1.3.2=r36h6115d3f_0
  - r-sourcetools=0.1.7=r36h29659fb_0
  - r-spatial=7.3_11=r36h96ca727_4
  - r-squarem=2017.10_1=r36h6115d3f_0
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-survival=2.44_1.1=r36h96ca727_0
  - r-sys=3.2=r36h96ca727_0
  - r-tibble=2.1.1=r36h96ca727_0
  - r-tidyr=0.8.3=r36h29659fb_0
  - r-tidyselect=0.2.5=r36h29659fb_0
  - r-tidyverse=1.2.1=r36h6115d3f_0
  - r-timedate=3043.102=r36h6115d3f_0
  - r-tinytex=0.12=r36h6115d3f_0
  - r-ttr=0.23_4=r36ha65eedd_0
  - r-utf8=1.1.4=r36h96ca727_0
  - r-uuid=0.1_2=r36h96ca727_4
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-whisker=0.3_2=r36h6115d3f_4
  - r-withr=2.1.2=r36h6115d3f_0
  - r-xfun=0.6=r36h6115d3f_0
  - r-xml2=1.2.0=r36h29659fb_0
  - r-xtable=1.8_4=r36h6115d3f_0
  - r-xts=0.11_2=r36h96ca727_0
  - r-yaml=2.2.0=r36h96ca727_0
  - r-zoo=1.8_6=r36h96ca727_0
  - readline=8.0=h7b6447c_0
  - rstudio=1.0.44=0
  - send2trash=1.5.0=py38_0
  - setuptools=47.3.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.32.2=h62c20be_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - tktable=2.10=h14c3975_0
  - tornado=6.0.4=py38h7b6447c_1
  - traitlets=4.3.3=py38_0
  - wcwidth=0.2.4=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - alabaster==0.7.12
    - async-generator==1.10
    - babel==2.8.0
    - chardet==3.0.4
    - click==7.1.2
    - colorama==0.4.3
    - docutils==0.16
    - gitdb==4.0.5
    - gitpython==3.1.3
    - idna==2.10
    - imagesize==1.2.0
    - ipywidgets==7.5.1
    - jupyter-book==0.7.1
    - jupyter-cache==0.2.2
    - jupyter-sphinx==0.2.4
    - latexcodec==2.0.1
    - libsass==0.20.0
    - markdown-it-py==0.4.7
    - myst-nb==0.8.3
    - myst-parser==0.9.0
    - nbclient==0.4.0
    - nbdime==2.0.0
    - nest-asyncio==1.3.3
    - oset==0.1.3
    - pybtex==0.22.2
    - pybtex-docutils==0.2.2
    - pydata-sphinx-theme==0.3.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - requests==2.24.0
    - smmap==3.0.4
    - snowballstemmer==2.0.0
    - sphinx==2.4.4
    - sphinx-book-theme==0.0.28
    - sphinx-copybutton==0.2.12
    - sphinx-togglebutton==0.2.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-bibtex==1.0.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlalchemy==1.3.18
    - urllib3==1.25.9
    - widgetsnbextension==3.5.1
prefix: /home/ronggolawe/anaconda3/envs/r-env

